#! /bin/sh
# postinst for upmpdcli

set -e

if [ "$1" = configure ]; then
    if ! getent passwd upmpdcli > /dev/null; then
	adduser --disabled-password --quiet --system \
	    --home /nonexistent --no-create-home --shell /bin/false upmpdcli
    fi
    if ! groups upmpdcli | cut -d' ' -f 3- | grep -q -w audio ; then
        usermod -a -G audio upmpdcli
    fi
fi

#DEBHELPER#

exit 0
